# Generated by Django 5.1 on 2025-02-25 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_app', '0009_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city_app.user'),
        ),
    ]
