# Generated by Django 5.1 on 2025-02-25 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_app', '0010_alter_chatsession_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('question', 'Question'), ('discussion', 'Discussion'), ('news', 'News'), ('announcement', 'Announcement'), ('guide', 'Guide'), ('meme', 'Meme'), ('other', 'Other')], default='discussion', max_length=50),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city_app.products')),
            ],
        ),
    ]
